sudo: required
services:
  - docker
before_install:
  - docker pull yglukhov/devel
script:
  - docker run -v "$(pwd):/project" -w /project yglukhov/nim-ui-base run "nimble install -y && nim tests ttf.nims"
